url: https://www.ashwinvaswani.github.io
baseurl: /new-website/

# Site settings
title: Welcome!
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Members names, titles and social links
people:
- name: Pranav Garg
  pic: alish
  position: GOD
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Alish Dipani
  pic: alish
  position: GOD2
  social:
    - title: twitter
      url: https://twitter.com/Alu57202
    - title: linkedin
      url: https://www.linkedin.com/in/alish-dipani/
    - title: google-plus
      url: https://github.com/alishdipani

- name: Sharad Chitlangia
  pic: alish
  position: GOD3
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Mehul Rastogi
  pic: alish
  position: GOD4
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Rijul Ganguly
  pic: alish
  position: GOD4
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Ashwin Vaswani
  pic: alish
  position: GOD4
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #


- name: Het Shah
  pic: alish
  position: GOD4
  social:
    - title: twitter
      url: https://twitter.com/het__shah
    - title: linkedin
      url: https://www.linkedin.com/in/het-shah163/
    - title: google-plus
      url: https://www.github.com/Het-Shah


- name: Rajaswa Patil
  pic: alish
  position: GOD4
  social:
    - title: twitter
      url: https://twitter.com/rajaswapatil
    - title: linkedin
      url: https://in.linkedin.com/in/rajaswa-patil
    - title: google-plus
      url: https://github.com/rajaswa


- name: Ajay Subramanium
  pic: alish
  position: GOD4
  social:
    - title: twitter
      url: https://twitter.com/ajaysub110
    - title: linkedin
      url: https://www.linkedin.com/in/ajaysub110
    - title: google-plus
      url: https://github.com/ajaysub110

- name: Aditya Ahuja
  pic: aditya
  position: GOD4
  social:
    - title: twitter
      url: https://twitter.com/adiah07
    - title: linkedin
      url: https://www.linkedin.com/in/aditya-ahuja-37b57114b/
    - title: google-plus
      url: https://github.com/adiah80

- name: Sauradeep Chakraborty
  pic: alish
  position: GOD4
  social:
    - title: twitter
      url: https://twitter.com/SauratheInferno
    - title: linkedin
      url: https://www.linkedin.com/in/souradeep-chakraborty-73a8607b/
    - title: google-plus
      url: https://github.com/sauradefy99

- name: Shangeth Rajaa
  pic: alish
  position: GOD4
  social:
    - title: twitter
      url: https://twitter.com/shangethr
    - title: linkedin
      url: https://www.linkedin.com/in/shangeth/
    - title: google-plus
      url: https://github.com/shangeth

- name: Pranav Mahajan
  pic: alish
  position: GOD4
  social:
    - title: twitter
      url: https://twitter.com/iam_mahajan
    - title: linkedin
      url: #
    - title: google-plus
      url: https://github.com/PranavMahajan25



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url: https://github.com/SforAiDl

# Postal address (add as many lines as necessary)
address:
  - line: BITS Pilani
  - line: K K Birla Goa Campus

# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-cayman
